version: "3.9"

services:
  backend:
    image: devsecopsacrnita.azurecr.io/backend:${APP_TAG}
    ports:
      - "8000:8000"
    restart: always

  frontend:
    image: devsecopsacrnita.azurecr.io/frontend:${APP_TAG}
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
